/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:d99bf54d-fe71-4646-8808-79f0315f5620",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_CbLBAKAnx",
    "aws_user_pools_web_client_id": "37dd5e91jp6qmi2bv7u84v9r1a",
    "oauth": {
        "domain": "profilesapp67d44721-67d44721-dev.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,http://localhost:5175/,http://localhost:5174/",
        "redirectSignOut": "http://localhost:3000/,http://localhost:5174/,http://localhost:5175/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://jpoqynefi5blnccnukpmso6qla.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-a2q7wgmopfb53dz7fzslh3eghq"
};


export default awsmobile;
